-- ============================================================
-- 견적원가 상세 기능 DDL (투자비, 제조경비, 판관비, 손익, 민감도, NPV)
-- ============================================================

-- ■ 견적정보 상세 (상세정보 탭)
CREATE TABLE IF NOT EXISTS PCM_EC_DETAIL (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    EC_VER         INTEGER      DEFAULT 1,
    RECV_DT        VARCHAR(10),
    SUBMIT_DT      VARCHAR(10),
    PRICE_COMP     VARCHAR(10),
    ORDER_TYPE     VARCHAR(20),
    FACTORY_TYPE   VARCHAR(10),
    FACTORY_CD     VARCHAR(50),
    CORP_TYPE      VARCHAR(10),
    CORP_CD        VARCHAR(50),
    ORDER_PROB     VARCHAR(10),
    ORDER_REASON   VARCHAR(500),
    COMPETITOR     VARCHAR(500),
    DEV_POSS       VARCHAR(500),
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_DETAIL PRIMARY KEY (TEN_ID, EC_PJT_CD, EC_VER)
);

-- ■ 원가코드/판가
CREATE TABLE IF NOT EXISTS PCM_EC_COST_CODE (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    COST_CD        VARCHAR(20)  NOT NULL,
    PROD_GRP       VARCHAR(20),
    COST_GRP       VARCHAR(50),
    COST_GRP_DESC  VARCHAR(200),
    EST_CURRENCY   VARCHAR(10),
    EST_PRICE      NUMERIC(18,2),
    MKT_CURRENCY   VARCHAR(10),
    MKT_PRICE      NUMERIC(18,2),
    SOP_YM         VARCHAR(7),
    EOP_YM         VARCHAR(7),
    SORT_NO        INTEGER      DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_COST_CODE PRIMARY KEY (TEN_ID, EC_PJT_CD, COST_CD)
);

-- ■ 수량/할인율 (연도별)
CREATE TABLE IF NOT EXISTS PCM_EC_QTY_DISC (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    COST_CD        VARCHAR(20)  NOT NULL,
    YEAR_VAL       VARCHAR(4)   NOT NULL,
    SALES_QTY      NUMERIC(18,0),
    DISC_RATE      NUMERIC(10,4),
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_QTY_DISC PRIMARY KEY (TEN_ID, EC_PJT_CD, COST_CD, YEAR_VAL)
);

-- ■ 담당자
CREATE TABLE IF NOT EXISTS PCM_EC_MANAGER (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    SEQ_NO         SERIAL,
    DEPT_TYPE      VARCHAR(20),
    USER_ID        VARCHAR(50),
    USER_NM        VARCHAR(100),
    ROLE_TYPE      VARCHAR(10),
    EMAIL          VARCHAR(200),
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_MANAGER PRIMARY KEY (TEN_ID, EC_PJT_CD, SEQ_NO)
);

-- ■ 일정
CREATE TABLE IF NOT EXISTS PCM_EC_SCHEDULE (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    TASK_CD        VARCHAR(20)  NOT NULL,
    TASK_NM        VARCHAR(200),
    START_DT       VARCHAR(10),
    END_DT         VARCHAR(10),
    ACTUAL_END_DT  VARCHAR(10),
    DELAY_DAYS     INTEGER      DEFAULT 0,
    SORT_NO        INTEGER      DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_SCHEDULE PRIMARY KEY (TEN_ID, EC_PJT_CD, TASK_CD)
);

-- ■ 수주결과
CREATE TABLE IF NOT EXISTS PCM_EC_ORDER_RESULT (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    ORDER_RESULT   VARCHAR(20),
    RESULT_RMK     VARCHAR(1000),
    ATTACH_FILE    VARCHAR(500),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_ORDER_RESULT PRIMARY KEY (TEN_ID, EC_PJT_CD)
);

-- ■ 라인투자비 (신규라인/기존라인)
CREATE TABLE IF NOT EXISTS PCM_EC_LINE_INVEST (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    LINE_SEQ       SERIAL,
    LINE_TYPE      VARCHAR(10),
    LINE_CD        VARCHAR(50),
    LINE_NM        VARCHAR(200),
    PROCESS_TYPE   VARCHAR(20),
    ACQ_AMT        NUMERIC(18,2)  DEFAULT 0,
    ACQ_CURRENCY   VARCHAR(10)    DEFAULT 'KRW',
    DEPR_START_YM  VARCHAR(7),
    CAPA_QTY       NUMERIC(18,0)  DEFAULT 0,
    AVAIL_RATE     NUMERIC(10,2)  DEFAULT 100,
    USE_RATE       NUMERIC(10,2)  DEFAULT 0,
    USEFUL_LIFE    INTEGER        DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_LINE_INVEST PRIMARY KEY (TEN_ID, EC_PJT_CD, LINE_SEQ)
);

-- ■ 라인투자비 설비 상세
CREATE TABLE IF NOT EXISTS PCM_EC_LINE_INVEST_DTL (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    LINE_SEQ       INTEGER      NOT NULL,
    DTL_SEQ        SERIAL,
    DTL_NM         VARCHAR(200),
    CURRENCY       VARCHAR(10),
    AMT            NUMERIC(18,2)  DEFAULT 0,
    ACQ_YEAR       VARCHAR(4),
    DEPR_START_YM  VARCHAR(7),
    CAPA_QTY       NUMERIC(18,0)  DEFAULT 0,
    USEFUL_LIFE    INTEGER        DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_LINE_DTL PRIMARY KEY (TEN_ID, EC_PJT_CD, LINE_SEQ, DTL_SEQ)
);

-- ■ 라인 C/T 배정 (원가코드별)
CREATE TABLE IF NOT EXISTS PCM_EC_LINE_CT (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    LINE_SEQ       INTEGER      NOT NULL,
    COST_CD        VARCHAR(20)  NOT NULL,
    USE_YN         CHAR(1)      DEFAULT 'N',
    EST_CT         NUMERIC(10,2)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_LINE_CT PRIMARY KEY (TEN_ID, EC_PJT_CD, LINE_SEQ, COST_CD)
);

-- ■ 기타투자비 (건구축물, 연구개발, 토지, 기타)
CREATE TABLE IF NOT EXISTS PCM_EC_OTHER_INVEST (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    INVEST_SEQ     SERIAL,
    INVEST_NM      VARCHAR(200),
    INVEST_TYPE    VARCHAR(20),
    CURRENCY       VARCHAR(10),
    ACQ_AMT        NUMERIC(18,2)  DEFAULT 0,
    DEPR_TYPE      VARCHAR(20),
    USEFUL_LIFE    INTEGER        DEFAULT 0,
    ACQ_YEAR       VARCHAR(4),
    DEPR_START_YM  VARCHAR(7),
    AVAIL_RATE     NUMERIC(10,2)  DEFAULT 100,
    USE_RATE       NUMERIC(10,2)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_OTHER_INVEST PRIMARY KEY (TEN_ID, EC_PJT_CD, INVEST_SEQ)
);

-- ■ 인원계획
CREATE TABLE IF NOT EXISTS PCM_EC_MANPOWER (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    MP_SEQ         SERIAL,
    MP_TYPE        VARCHAR(20),
    MP_NM          VARCHAR(200),
    PROCESS_TYPE   VARCHAR(20),
    CURRENCY       VARCHAR(10),
    AVG_SALARY     NUMERIC(18,2)  DEFAULT 0,
    Y1_CNT         NUMERIC(10,1)  DEFAULT 0,
    Y2_CNT         NUMERIC(10,1)  DEFAULT 0,
    Y3_CNT         NUMERIC(10,1)  DEFAULT 0,
    Y4_CNT         NUMERIC(10,1)  DEFAULT 0,
    Y5_CNT         NUMERIC(10,1)  DEFAULT 0,
    Y6_CNT         NUMERIC(10,1)  DEFAULT 0,
    Y7_CNT         NUMERIC(10,1)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_MANPOWER PRIMARY KEY (TEN_ID, EC_PJT_CD, MP_SEQ)
);

-- ■ 제조경비
CREATE TABLE IF NOT EXISTS PCM_EC_MFG_COST (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    COST_CD        VARCHAR(20)  NOT NULL,
    YEAR_VAL       VARCHAR(4)   NOT NULL DEFAULT '1',
    WAGE_RAISE_RATE    NUMERIC(10,4)  DEFAULT 0,
    PRICE_RAISE_RATE   NUMERIC(10,4)  DEFAULT 0,
    PROD_DIRECT_RATE   NUMERIC(10,4)  DEFAULT 0,
    LABOR_COST_RATE    NUMERIC(10,4)  DEFAULT 0,
    OTHER_MFG_RATE     NUMERIC(10,4)  DEFAULT 0,
    MOLD_COST          NUMERIC(18,2)  DEFAULT 0,
    OUTSRC_COST        NUMERIC(18,2)  DEFAULT 0,
    OUTSRC_RATE        NUMERIC(10,4)  DEFAULT 0,
    DIRECT_LABOR       NUMERIC(18,2)  DEFAULT 0,
    INDIRECT_LABOR     NUMERIC(18,2)  DEFAULT 0,
    PROD_DIRECT_EXP    NUMERIC(18,2)  DEFAULT 0,
    LABOR_RELATED_EXP  NUMERIC(18,2)  DEFAULT 0,
    OTHER_MFG_EXP      NUMERIC(18,2)  DEFAULT 0,
    DEPR_BUILDING      NUMERIC(18,2)  DEFAULT 0,
    DEPR_LINE          NUMERIC(18,2)  DEFAULT 0,
    DEPR_OTHER         NUMERIC(18,2)  DEFAULT 0,
    RND_COST           NUMERIC(18,2)  DEFAULT 0,
    OTHER_EXP          NUMERIC(18,2)  DEFAULT 0,
    TOTAL_MFG_COST     NUMERIC(18,2)  DEFAULT 0,
    CALC_STS           VARCHAR(10)    DEFAULT 'N',
    RMK                VARCHAR(1000),
    REGR_ID            VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID            VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_MFG_COST PRIMARY KEY (TEN_ID, EC_PJT_CD, COST_CD, YEAR_VAL)
);

-- ■ 판매관리비
CREATE TABLE IF NOT EXISTS PCM_EC_SGA_COST (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    COST_CD        VARCHAR(20)  NOT NULL,
    YEAR_VAL       VARCHAR(4)   NOT NULL DEFAULT '1',
    SALES_LABOR_RATE   NUMERIC(10,4)  DEFAULT 0,
    TRANSPORT_RATE     NUMERIC(10,4)  DEFAULT 0,
    EXPORT_RATE        NUMERIC(10,4)  DEFAULT 0,
    WARRANTY_RATE      NUMERIC(10,4)  DEFAULT 0,
    ADVERTISING_RATE   NUMERIC(10,4)  DEFAULT 0,
    RESEARCH_RATE      NUMERIC(10,4)  DEFAULT 0,
    ASSET_RATE         NUMERIC(10,4)  DEFAULT 0,
    PERSONNEL_RATE     NUMERIC(10,4)  DEFAULT 0,
    OTHER_RATE         NUMERIC(10,4)  DEFAULT 0,
    TOTAL_SGA_COST     NUMERIC(18,2)  DEFAULT 0,
    CALC_STS           VARCHAR(10)    DEFAULT 'N',
    RMK                VARCHAR(1000),
    REGR_ID            VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID            VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_SGA_COST PRIMARY KEY (TEN_ID, EC_PJT_CD, COST_CD, YEAR_VAL)
);

-- ■ 손익계산서
CREATE TABLE IF NOT EXISTS PCM_EC_PL_STMT (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    VIEW_TYPE      VARCHAR(10)  NOT NULL,
    VIEW_KEY       VARCHAR(50)  NOT NULL,
    YEAR_VAL       VARCHAR(4)   NOT NULL,
    SALES_AMT      NUMERIC(18,2)  DEFAULT 0,
    MAT_COST       NUMERIC(18,2)  DEFAULT 0,
    LABOR_COST     NUMERIC(18,2)  DEFAULT 0,
    MFG_COST       NUMERIC(18,2)  DEFAULT 0,
    TOTAL_MFG_COST NUMERIC(18,2)  DEFAULT 0,
    GROSS_PROFIT   NUMERIC(18,2)  DEFAULT 0,
    SGA_COST       NUMERIC(18,2)  DEFAULT 0,
    OPER_INCOME    NUMERIC(18,2)  DEFAULT 0,
    OPER_MARGIN    NUMERIC(10,4)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_PL_STMT PRIMARY KEY (TEN_ID, EC_PJT_CD, VIEW_TYPE, VIEW_KEY, YEAR_VAL)
);

-- ■ 민감도 분석
CREATE TABLE IF NOT EXISTS PCM_EC_SENSITIVITY (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    SENS_VER       INTEGER      NOT NULL DEFAULT 1,
    SENS_NM        VARCHAR(200),
    END_YN         CHAR(1)      DEFAULT 'N',
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_SENS PRIMARY KEY (TEN_ID, EC_PJT_CD, SENS_VER)
);

-- ■ 민감도 분석 변수
CREATE TABLE IF NOT EXISTS PCM_EC_SENSITIVITY_VAR (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    SENS_VER       INTEGER      NOT NULL,
    VAR_TYPE       VARCHAR(20)  NOT NULL,
    VAR_NM         VARCHAR(200),
    BEFORE_VAL     NUMERIC(18,4)  DEFAULT 0,
    AFTER_VAL      NUMERIC(18,4)  DEFAULT 0,
    YEAR_VAL       VARCHAR(4)   NOT NULL DEFAULT '',
    COST_CD        VARCHAR(20)  NOT NULL DEFAULT '',
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_SENS_VAR PRIMARY KEY (TEN_ID, EC_PJT_CD, SENS_VER, VAR_TYPE, YEAR_VAL, COST_CD)
);

-- ■ 자금조달계획
CREATE TABLE IF NOT EXISTS PCM_EC_FUND_PLAN (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    FUND_SEQ       SERIAL,
    SOURCE_TYPE    VARCHAR(20),
    INTEREST_RATE  NUMERIC(10,4)  DEFAULT 0,
    CURRENCY       VARCHAR(10),
    Y1_AMT         NUMERIC(18,2)  DEFAULT 0,
    Y2_AMT         NUMERIC(18,2)  DEFAULT 0,
    Y3_AMT         NUMERIC(18,2)  DEFAULT 0,
    Y4_AMT         NUMERIC(18,2)  DEFAULT 0,
    Y5_AMT         NUMERIC(18,2)  DEFAULT 0,
    Y6_AMT         NUMERIC(18,2)  DEFAULT 0,
    Y7_AMT         NUMERIC(18,2)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_FUND_PLAN PRIMARY KEY (TEN_ID, EC_PJT_CD, FUND_SEQ)
);

-- ■ 운전자본 회전율
CREATE TABLE IF NOT EXISTS PCM_EC_WORK_CAPITAL (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    AR_TURNOVER    NUMERIC(10,4)  DEFAULT 0,
    INV_TURNOVER   NUMERIC(10,4)  DEFAULT 0,
    AP_TURNOVER    NUMERIC(10,4)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_WORK_CAP PRIMARY KEY (TEN_ID, EC_PJT_CD)
);

-- ■ NPV 분석
CREATE TABLE IF NOT EXISTS PCM_EC_NPV (
    TEN_ID         VARCHAR(18)  NOT NULL,
    EC_PJT_CD      VARCHAR(20)  NOT NULL,
    ANALYSIS_VER   INTEGER      NOT NULL DEFAULT 1,
    ANALYSIS_TYPE  VARCHAR(20),
    WACC_RATE      NUMERIC(10,4)  DEFAULT 0,
    NPV_VAL        NUMERIC(18,2)  DEFAULT 0,
    IRR_VAL        NUMERIC(10,4)  DEFAULT 0,
    PAYBACK_PERIOD NUMERIC(10,2)  DEFAULT 0,
    PI_VAL         NUMERIC(10,4)  DEFAULT 0,
    RMK            VARCHAR(1000),
    REGR_ID        VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID        VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EC_NPV PRIMARY KEY (TEN_ID, EC_PJT_CD, ANALYSIS_VER)
);
