-- ============================================================
-- 기준정보 Excel 데이터 Import (자동 생성)
-- ============================================================

-- ■ 1.제품 → T033 (제품군)
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T033','SEAT','SEAT',1,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T033','TM','T/M',2,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T033','AXLE','AXLE',3,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;

-- ■ 2.OEM → CUST, T034, T035, T015
INSERT INTO PCM_COM_GRP_CD (TEN_ID,GRP_CD,GRP_NM,USE_YN,SORT_NO,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T034','국가','Y',34,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID,GRP_CD,GRP_NM,USE_YN,SORT_NO,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T035','법인','Y',35,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','CUST','BMW','BMW',1,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','CUST','GM','GM',2,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','CUST','HMC','HMC',3,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','CUST','KMC','KMC',4,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T034','KOR','대한민국',1,'Y','KRW','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T034','USA','미국',2,'Y','USD','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T034','CHN','중국',3,'Y','CNY','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T035','CORP01','다이모스',1,'Y','KOR','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T015','10001','서산공장',1,'Y',NULL,'다이모스','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T015','10002','동탄공장',2,'Y',NULL,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;

-- ■ 3.수주탈락 → T016
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','01','목표가 대비 차이 과다',1,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','02','설비 투자비 과다',2,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','03','고객사 정책',3,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','04','개발기간 부족',4,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','05','미보유 기술 적용',5,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','06','고객신뢰 미충족',6,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','07','경쟁사의 저가 수주',7,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T016','99','기타',8,'Y','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;

-- ■ 4.표준일정 → PCM_STD_SCHEDULE
DELETE FROM PCM_STD_SCHEDULE WHERE TEN_ID = 'T001';
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G10 견적원가 Code 생성',1,'영업','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G20 견적원가 대상 등록',1,'영업','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G30 BOM(master list)작성',5,'설계','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G40 신규자재 설계원가 작성',4,'설계원가','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G50 신규자재 구매추정가 작성',4,'구매','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G60 재료비 단가 검토',3,'원가','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G70 인원/투자비 산정',9,'생기','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','G80 견적원가 산출 및 수익성 분석',2,'원가','견적단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T10 목표원가 Code 생성',1,'원가관리','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T20 목표수익률 협의',3,'All','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T30 부문별 배부 Guide 수립 및 
배부 금액 확정',5,'All','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T40 부문별 원가절감계획 수립/등록',5,'영업','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T40 부문별 원가절감계획 수립/등록',5,'생기','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T40 부문별 원가절감계획 수립/등록',5,'설계','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T40 부문별 원가절감계획 수립/등록',5,'구매','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T50 경영진 보고',1,'원가관리','목표단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E10 견적원가 Code 생성과 
기초정보 등록요청',1,'원가관리','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E20 BOM 재검토',4,'설계','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E30 BOM Mapping',5,'설계','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E40 신규 인원 , 투자비,  생산 라인 및 C/T 재검토',5,'생기','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E50 신규자재 설계원가 재검토',4,'설계원가','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E60 신규자재 구매추정가 재검토',4,'구매','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E70 재료비 단가 검토',1,'원가관리','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E80 현상원가 산출',3,'원가관리','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E90 현상원가 차이 분석 및 
상세원인 등록',7,'All','현상단계','system',NOW(),'system',NOW());
INSERT INTO PCM_STD_SCHEDULE (TEN_ID,TASK_NM,LEAD_DAYS,DEPT_CD,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','E99 달성도 평가와 목표 재배부',5,'원가관리','현상단계','system',NOW(),'system',NOW());

-- ■ 5.손익계정관리 → PCM_PL_ITEM
DELETE FROM PCM_PL_ITEM WHERE TEN_ID = 'T001';
-- 손익 트리 구조: 최상위 집계 항목
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL000','손익합계',NULL,'S',1,0,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL100','매출액','PL000','S',2,1,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL200','매출원가','PL000','S',2,2,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL210','재료비','PL200','S',3,1,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL220','노무비','PL200','S',3,2,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL230','제조경비','PL200','S',3,3,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL300','매출총이익','PL000','S',2,3,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL400','판관비','PL000','S',2,4,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL500','영업이익','PL000','S',2,5,NULL,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
-- 상세 항목 (Excel 데이터)
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL110','견적기준가(매출)','PL100','V',3,1,'REDU:Y, CALC:원가코드별 입력','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL211','재료비_C/O','PL210','V',4,3,'REDU:Y, CALC:원가코드별 sum(BOM의 자재 단가 X 수량)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL212','재료비_신규','PL210','V',4,4,'REDU:Y, CALC:원가코드별 sum(BOM의 자재 단가 X 수량)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL221','직접노무비_기존','PL220','V',4,5,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL222','직접노무비_신규','PL220','V',4,6,'REDU:Y, CALC:신규 직접 인원 연간 인건비 → 제품 사양별 C/T 기준 배부(수량 X 추정 C/T 값 고려)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL223','간접노무비_기존','PL220','V',4,7,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL224','간접노무비_신규','PL220','V',4,8,'REDU:Y, CALC:신규 간접 인원 연간 인건비 → 직접노무비 배부 비율 준용하여 제품 사양에 배부','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL231','인건비성경비_기존','PL230','V',4,9,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL232','인건비성경비_신규','PL230','V',4,10,'REDU:Y, CALC:%%%','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL233','기타제조경비_기존','PL230','V',4,11,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL234','기타제조경비_신규','PL230','V',4,12,'REDU:Y, CALC:%%%','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL235','연구개발비','PL230','V',4,13,'REDU:Y, CALC:신규 투자 내역(연구비)에서 연간 비용 계산','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL236','감가상각비_토지_기존','PL230','V',4,14,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T(감가상각비 별도 로직 추가)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL237','감가상각비_건구축물_기존','PL230','V',4,15,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T(감가상각비 별도 로직 추가)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL238','감가상각비_생산라인_기존','PL230','V',4,16,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T(감가상각비 별도 로직 추가)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL239','감가상각비_기타_기존','PL230','V',4,17,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T(감가상각비 별도 로직 추가)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL240','감가상각비_토지_신규','PL230','V',4,18,'REDU:Y, CALC:신규 투자 내역 → 연간 감가비 계산 및 단위당 감가비 산정','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL241','감가상각비_건구축물_신규','PL230','V',4,19,'REDU:Y, CALC:신규 투자 내역 → 연간 감가비 계산 및 단위당 감가비 산정','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL242','감가상각비_생산라인_신규','PL230','V',4,20,'REDU:Y, CALC:신규 투자 내역 → 연간 감가비 계산 및 단위당 감가비 산정','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL243','감가상각비_기타_신규','PL230','V',4,21,'REDU:Y, CALC:신규 투자 내역 → 연간 감가비 계산 및 단위당 감가비 산정','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL244','외주가공비','PL230','V',4,22,'REDU:Y, CALC:직접 입력(신규)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL245','생산직접경비_기존','PL230','V',4,23,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL246','전력비_기존','PL230','V',4,24,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL247','전력비_신규','PL230','V',4,25,'REDU:Y, CALC:&&&&&','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL248','용수비_기존','PL230','V',4,26,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL249','용수비_신규','PL230','V',4,27,'REDU:Y, CALC:&&&&&','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL250','연료비_기존','PL230','V',4,28,'ERP:Y, REDU:Y, CALC:기존 라인 C/T 당 원가 X 신규 제품 추정 C/T','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL251','연료비_신규','PL230','V',4,29,'REDU:Y, CALC:&&&&&','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL252','금형비','PL230','V',4,30,'REDU:Y, CALC:직접 입력(신규)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL253','기타경비_신규','PL230','V',4,31,'REDU:Y, CALC:투자 입력 기타 항목 중 당기 비용 처리 대상','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL401','판관인건비_기존','PL400','V',3,32,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL402','판관인건비_신규','PL400','V',3,33,'REDU:Y, CALC:신규 투자 내역 → 연간 판관인건비 계산 및 단위당 금액 산정','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL403','운반비','PL400','V',3,34,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL404','수출비','PL400','V',3,35,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL405','품질보증비','PL400','V',3,36,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL406','광고선전비','PL400','V',3,37,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL407','연구비','PL400','V',3,38,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL408','자산비용','PL400','V',3,39,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL409','인적비용(4대보험등)','PL400','V',3,40,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID,ITEM_CD,ITEM_NM,UP_ITEM_CD,ITEM_TYPE,LVL,SORT_NO,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','PL410','기타판관비','PL400','V',3,41,'BIZ:Y, CALC:매출 X 전년도 사업실적 비율(공장별)','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;

-- ■ 5.1.제조경비계정 매핑 → PCM_ERP_ACCT_MAP
DELETE FROM PCM_ERP_ACCT_MAP WHERE TEN_ID = 'T001';
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','702101','702200','직접노무비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','702201','703100','간접노무비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','703101','703104','직접노무비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','703105','704100','간접노무비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','704101','704800','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','704801','704900','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','704901','705100','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','705101','707302','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','707303','707504','생산직접경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','707505','707998','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','707999','707102','생산직접경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','707103','710100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','710101','711100','생산직접경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711101','711101','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711102','711104','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711105','711105','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711106','711107','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711108','711108','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711109','711198','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','711199','712100','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','712101','715100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','715101','716100','전력비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','716101','717100','용수비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','717101','718100','연료비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','718101','719100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','719101','719101','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','719102','720100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720101','720103','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720104','720104','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720105','720108','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720109','720109','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720110','720110','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720111','720112','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','720113','721100','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','721101','723100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','723101','724100','인건비성경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','724101','724102','감가상각비_건구축물_기존','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','724103','724103','감가상각비_생산라인_기존','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','724104','724104','감가상각비_기타_기존','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','724105','724105','감가상각비_생산라인_기존','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','724106','725100','감가상각비_기타_기존','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','725101','727100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','727101','727104','생산직접경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','727105','727198','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','727199','728100','생산직접경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','728101','740100','기타제조경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','740101','740103','생산직접경비','system',NOW(),'system',NOW());
INSERT INTO PCM_ERP_ACCT_MAP (TEN_ID,FROM_CD,TO_CD,ITEM_NM,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','740104','749999','기타제조경비','system',NOW(),'system',NOW());

-- ■ 6.부서및인원 → T036, T037
INSERT INTO PCM_COM_GRP_CD (TEN_ID,GRP_CD,GRP_NM,USE_YN,SORT_NO,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T036','인원','Y',36,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID,GRP_CD,GRP_NM,USE_YN,SORT_NO,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T037','부서','Y',37,'system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,ATTR3,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T036','1234567','배병희',1,'Y','차장','원가관리','다이모스','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,ATTR3,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T036','2345678','***',2,'Y','대리','구매','다이모스','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,ATTR3,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T036','9876543','&&&',3,'Y','차장','설계','다이모스','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,ATTR3,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T036','3456789','%%%',4,'Y','과장','설계원가','다이모스','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID,GRP_CD,DTL_CD,CD_NM,SORT_NO,USE_YN,ATTR1,ATTR2,ATTR3,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','T036','3456000','김지원',5,'Y','대리','원가관리','다이모스','system',NOW(),'system',NOW()) ON CONFLICT DO NOTHING;

-- ■ 7.원가산출 → PCM_PROD_LINE, PCM_EXCH_RATE
DELETE FROM PCM_EXCH_RATE WHERE TEN_ID = 'T001';
-- 환율 데이터 (Excel Sheet 7)
INSERT INTO PCM_EXCH_RATE (TEN_ID,APPLY_YEAR,FROM_CUR,TO_CUR,EXCH_RATE,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2012','USD','KRW',970,'system',NOW(),'system',NOW());
INSERT INTO PCM_EXCH_RATE (TEN_ID,APPLY_YEAR,FROM_CUR,TO_CUR,EXCH_RATE,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2012','EUR','KRW',1350,'system',NOW(),'system',NOW());
INSERT INTO PCM_EXCH_RATE (TEN_ID,APPLY_YEAR,FROM_CUR,TO_CUR,EXCH_RATE,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2012','JPY','KRW',1500,'system',NOW(),'system',NOW());
INSERT INTO PCM_EXCH_RATE (TEN_ID,APPLY_YEAR,FROM_CUR,TO_CUR,EXCH_RATE,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013','USD','KRW',1000,'system',NOW(),'system',NOW());
INSERT INTO PCM_EXCH_RATE (TEN_ID,APPLY_YEAR,FROM_CUR,TO_CUR,EXCH_RATE,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013','EUR','KRW',1400,'system',NOW(),'system',NOW());
INSERT INTO PCM_EXCH_RATE (TEN_ID,APPLY_YEAR,FROM_CUR,TO_CUR,EXCH_RATE,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013','JPY','KRW',1600,'system',NOW(),'system',NOW());

-- ■ 8.사업실적 → PCM_BIZ_PERF_RATE
DELETE FROM PCM_BIZ_PERF_RATE WHERE TEN_ID = 'T001';
-- 사업실적 비율 (Excel Sheet 8: 다이모스 2013)
INSERT INTO PCM_BIZ_PERF_RATE (TEN_ID,BASE_YEAR,CORP_CD,ITEM_CD,PERF_RATE,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013',NULL,'3010',0.0103,'판관인건비','system',NOW(),'system',NOW());
INSERT INTO PCM_BIZ_PERF_RATE (TEN_ID,BASE_YEAR,CORP_CD,ITEM_CD,PERF_RATE,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013',NULL,'3110',0.0123,'운반비','system',NOW(),'system',NOW());
INSERT INTO PCM_BIZ_PERF_RATE (TEN_ID,BASE_YEAR,CORP_CD,ITEM_CD,PERF_RATE,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013',NULL,'3120',0.025,'수출비','system',NOW(),'system',NOW());
INSERT INTO PCM_BIZ_PERF_RATE (TEN_ID,BASE_YEAR,CORP_CD,ITEM_CD,PERF_RATE,RMK,REGR_ID,REG_DTTM,MODR_ID,MOD_DTTM) VALUES ('T001','2013',NULL,'3040',0.0033,'품질보증비','system',NOW(),'system',NOW());
