-- ============================================================
-- 기준정보 관리 DDL + 샘플 데이터 (DataInitController에서 실행)
-- ============================================================

-- ■ 그룹코드 테이블
CREATE TABLE IF NOT EXISTS PCM_COM_GRP_CD (
    TEN_ID      VARCHAR(18)  NOT NULL,
    GRP_CD      VARCHAR(18)  NOT NULL,
    GRP_NM      VARCHAR(200) NOT NULL,
    USE_YN      CHAR(1)      DEFAULT 'Y',
    SORT_NO     INTEGER      DEFAULT 0,
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_COM_GRP_CD PRIMARY KEY (TEN_ID, GRP_CD)
);

-- ■ 상세코드 테이블
CREATE TABLE IF NOT EXISTS PCM_COM_DTL_CD (
    TEN_ID      VARCHAR(18)  NOT NULL,
    GRP_CD      VARCHAR(18)  NOT NULL,
    DTL_CD      VARCHAR(50)  NOT NULL,
    CD_NM       VARCHAR(200) NOT NULL,
    SORT_NO     INTEGER      DEFAULT 0,
    USE_YN      CHAR(1)      DEFAULT 'Y',
    ATTR1       VARCHAR(200),
    ATTR2       VARCHAR(200),
    ATTR3       VARCHAR(200),
    ATTR4       VARCHAR(200),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_COM_DTL_CD PRIMARY KEY (TEN_ID, GRP_CD, DTL_CD)
);

-- ■ 법인세율
CREATE TABLE IF NOT EXISTS PCM_CORP_TAX (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    COUNTRY_NM  VARCHAR(100),
    BASE_YEAR   VARCHAR(4),
    APPLY_YEAR  VARCHAR(4),
    TAX_RATE    NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_CORP_TAX PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ CRP
CREATE TABLE IF NOT EXISTS PCM_CRP (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    COUNTRY_NM  VARCHAR(100),
    BASE_YEAR   VARCHAR(4),
    CRP_VAL     NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_CRP PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ WACC Betau
CREATE TABLE IF NOT EXISTS PCM_BETAU (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    BASE_YEAR   VARCHAR(4),
    BIZ_UNIT    VARCHAR(18),
    BETAU_VAL   NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_BETAU PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 기존 생산라인
CREATE TABLE IF NOT EXISTS PCM_PROD_LINE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    BASE_YEAR   VARCHAR(4),
    PLANT_CD    VARCHAR(50),
    LINE_NM     VARCHAR(200),
    PROD_NM     VARCHAR(200),
    CAPACITY    BIGINT,
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_PROD_LINE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 손익 항목 (트리)
CREATE TABLE IF NOT EXISTS PCM_PL_ITEM (
    TEN_ID      VARCHAR(18)  NOT NULL,
    ITEM_CD     VARCHAR(50)  NOT NULL,
    ITEM_NM     VARCHAR(200),
    UP_ITEM_CD  VARCHAR(50),
    ITEM_TYPE   CHAR(1)      DEFAULT 'V',
    LVL         INTEGER      DEFAULT 1,
    SORT_NO     INTEGER      DEFAULT 0,
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_PL_ITEM PRIMARY KEY (TEN_ID, ITEM_CD)
);

-- ■ 사업 실적 비율
CREATE TABLE IF NOT EXISTS PCM_BIZ_PERF_RATE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    BASE_YEAR   VARCHAR(4),
    CORP_CD     VARCHAR(50),
    BIZ_UNIT    VARCHAR(18),
    ITEM_CD     VARCHAR(50),
    PERF_RATE   NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_BIZ_PERF_RATE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 환율
CREATE TABLE IF NOT EXISTS PCM_EXCH_RATE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    APPLY_YEAR  VARCHAR(4),
    FROM_CUR    VARCHAR(10),
    TO_CUR      VARCHAR(10),
    EXCH_RATE   NUMERIC(18,6),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EXCH_RATE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 인상율
CREATE TABLE IF NOT EXISTS PCM_RAISE_RATE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    APPLY_YEAR  VARCHAR(4),
    CORP_CD     VARCHAR(50),
    PLANT_CD    VARCHAR(50),
    ITEM_CD     VARCHAR(50),
    RAISE_RATE  NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_RAISE_RATE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 표준 일정
CREATE TABLE IF NOT EXISTS PCM_STD_SCHEDULE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    TASK_NM     VARCHAR(200),
    LEAD_DAYS   INTEGER,
    DEPT_CD     VARCHAR(50),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_STD_SCHEDULE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 원가 절감 활동 유형
CREATE TABLE IF NOT EXISTS PCM_COST_REDU_TYPE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    ITEM_CD     VARCHAR(50),
    CLASS1      VARCHAR(200),
    CLASS2      VARCHAR(200),
    CLASS3      VARCHAR(200),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_COST_REDU_TYPE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ ERP 제조원가 계정 매핑
CREATE TABLE IF NOT EXISTS PCM_ERP_ACCT_MAP (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    FROM_CD     VARCHAR(50),
    TO_CD       VARCHAR(50),
    ITEM_NM     VARCHAR(200),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_ERP_ACCT_MAP PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 절감대상 원가항목 및 담당부서
CREATE TABLE IF NOT EXISTS PCM_REDU_TGT_DEPT (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    ITEM_NM     VARCHAR(200),
    DTL_ITEM_NM VARCHAR(200),
    DEPT_CD     VARCHAR(50),
    RESP_RATE   NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM TIMESTAMPTZ,
    CONSTRAINT PK_PCM_REDU_TGT_DEPT PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ============================================================
-- 샘플 데이터
-- ============================================================

-- ■ 그룹코드
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','Rf','무위험이자율','Y',1,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','Rm','시장수익률기대값','Y',2,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T001','등급','Y',3,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T002','수주유형','Y',4,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','견적진행상태','Y',5,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T004','사업부','Y',6,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T005','담당자롤','Y',7,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T006','공정','Y',8,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T007','인력구분','Y',9,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T008','투자항목','Y',10,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T009','생산법인','Y',11,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T010','배부방식','Y',12,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T011','금액/비율','Y',13,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','CUST','고객사','Y',14,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T015','공장구분','Y',15,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T016','수주탈락사유','Y',16,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T017','손익항목특성','Y',17,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T018','인상률','Y',18,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T019','계정항목','Y',19,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T020','원가코드그룹','Y',20,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T021','부문','Y',21,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T022','ROLE','Y',22,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T023','지분구성','Y',23,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T024','달성도평가차수','Y',24,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T025','투자비진행상태','Y',25,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T026','금액구분1','Y',26,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T027','금액구분2','Y',27,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T028','감가상각구분','Y',28,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T029','재료비진행상태','Y',29,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T030','아이템구분','Y',30,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T031','자금조달구분','Y',31,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T032','차종','Y',32,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_GRP_CD (TEN_ID, GRP_CD, GRP_NM, USE_YN, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T033','제품군','Y',33,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- ■ 상세코드 샘플
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T004','PT','PT (구동계)',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T004','SEAT','SEAT (시트)',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T001','A','A등급',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T001','B','B등급',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T001','C','C등급',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T033','TM','TM',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T033','AXLE','AXLE',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T033','SEAT','SEAT',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, ATTR1, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','CUST','HMC','현대자동차',1,'Y','5.0','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, ATTR1, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','CUST','KIA','기아자동차',2,'Y','4.5','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, ATTR1, ATTR2, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T015','P01','화성공장',1,'Y','CORP01','현대다이모스(주)','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, ATTR1, ATTR2, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T015','P02','광주공장',2,'Y','CORP01','현대다이모스(주)','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T017','V','값',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T017','S','집계',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T009','KR','한국법인',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T009','CN','중국법인',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T009','US','미국법인',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- ■ 크로스모듈 연계 상세코드 (EC/TC/CC 모듈에서 참조)

-- T002 수주유형
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T002','01','공개입찰',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T002','02','전략수주',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T002','03','기타',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T003 견적진행상태
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','01','등록',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','02','구성완료',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','03','산출중',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','04','견적제출',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','05','수주확정',5,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T003','06','탈락',6,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T005 담당자롤
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T005','PM','PM',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T005','DESIGN','설계담당',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T005','PURCH','구매담당',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T005','COST','원가담당',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T005','QA','품질담당',5,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T006 공정
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T006','MACH','가공',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T006','ASSY','조립',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T006','HEAT','열처리',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T006','SEAT','SEAT',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T008 투자항목
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T008','LINE','생산라인',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T008','MOLD','금형',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T008','BLDG','건구축물',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T008','ETC','기타설비',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T010 배부방식
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T010','QTY','수량기준',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T010','AMT','금액기준',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T010','RATE','비율기준',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T011 금액/비율
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T011','AMT','금액',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T011','RATE','비율',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T020 원가코드그룹
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T020','MAT','재료비',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T020','LABOR','노무비',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T020','MFG','제조경비',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T020','SGA','판매관리비',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T021 부문
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T021','DESIGN','설계',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T021','PURCH','구매',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T021','MFG','생산기술',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T021','COST','원가기획',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T032 차종
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T032','SED','세단',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T032','SUV','SUV',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T032','EV','전기차',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T032','CV','상용차',4,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T007 인력구분
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T007','DIRECT','직접인원',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T007','INDIRECT','간접인원',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T024 달성도평가차수
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T024','1','1차',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T024','2','2차',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T024','3','3차',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- T028 감가상각구분
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T028','BLDG','건구축물',1,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T028','LINE','생산라인',2,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_COM_DTL_CD (TEN_ID, GRP_CD, DTL_CD, CD_NM, SORT_NO, USE_YN, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','T028','ETC','기타',3,'Y','system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;

-- ■ 손익 항목 샘플
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL000','손익합계',NULL,'S',1,1,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL100','매출액','PL000','S',2,1,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL110','제품매출','PL100','V',3,1,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL200','매출원가','PL000','S',2,2,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL210','재료비','PL200','V',3,1,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL220','노무비','PL200','V',3,2,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL230','제조경비','PL200','V',3,3,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL300','매출총이익','PL000','S',2,3,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL400','판관비','PL000','S',2,4,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PCM_PL_ITEM (TEN_ID, ITEM_CD, ITEM_NM, UP_ITEM_CD, ITEM_TYPE, LVL, SORT_NO, REGR_ID, REG_DTTM, MODR_ID, MOD_DTTM) VALUES
('T001','PL500','영업이익','PL000','S',2,5,'system',NOW(),'system',NOW())
ON CONFLICT DO NOTHING;
