-- ============================================================
-- 목표원가 + 현상원가 상세 테이블 초기화
-- ============================================================

-- ═══════════════════════════════════════════
-- 1. 목표원가 상세 테이블
-- ═══════════════════════════════════════════

-- 1-1. 목표원가 담당자
DROP TABLE IF EXISTS PCM_TGT_MANAGER CASCADE;
CREATE TABLE PCM_TGT_MANAGER (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    MGR_SEQ      INTEGER      NOT NULL,
    DEPT_DIV     VARCHAR(18),
    MGR_NM       VARCHAR(100),
    POSITION     VARCHAR(50),
    DEPT_NM      VARCHAR(100),
    ROLE_CD      VARCHAR(18),
    EMAIL        VARCHAR(200),
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_MANAGER PRIMARY KEY (TEN_ID, TGT_PJT_CD, MGR_SEQ)
);

-- 1-2. 목표원가 대표사양
DROP TABLE IF EXISTS PCM_TGT_SPEC CASCADE;
CREATE TABLE PCM_TGT_SPEC (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    SPEC_SEQ     INTEGER      NOT NULL,
    EC_PJT_CD    VARCHAR(18),
    TGT_COST_CD  VARCHAR(18),
    PROD_GRP     VARCHAR(18),
    CAR_TYPE     VARCHAR(100),
    OEM_NM       VARCHAR(100),
    SPEC_DESC    VARCHAR(500),
    SEL_YN       CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_SPEC PRIMARY KEY (TEN_ID, TGT_PJT_CD, SPEC_SEQ)
);

-- 1-3. 목표원가 판가정보
DROP TABLE IF EXISTS PCM_TGT_PRICE CASCADE;
CREATE TABLE PCM_TGT_PRICE (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    PRICE_SEQ    INTEGER      NOT NULL,
    SPEC_DESC    VARCHAR(500),
    TGT_COST_CD  VARCHAR(18),
    CURRENCY     VARCHAR(10),
    EST_SELL_PRICE NUMERIC(18,2) DEFAULT 0,
    SOP_YM       VARCHAR(7),
    EOP_YM       VARCHAR(7),
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_PRICE PRIMARY KEY (TEN_ID, TGT_PJT_CD, PRICE_SEQ)
);

-- 1-4. 목표원가 수량/할인율
DROP TABLE IF EXISTS PCM_TGT_QTY_DISC CASCADE;
CREATE TABLE PCM_TGT_QTY_DISC (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    QTY_SEQ      INTEGER      NOT NULL,
    SPEC_DESC    VARCHAR(500),
    TGT_COST_CD  VARCHAR(18),
    YEAR_VAL     VARCHAR(4),
    QTY          NUMERIC(18,2) DEFAULT 0,
    DISC_RATE    NUMERIC(8,4)  DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_QTY_DISC PRIMARY KEY (TEN_ID, TGT_PJT_CD, QTY_SEQ)
);

-- 1-5. 목표원가 개발/평가일정
DROP TABLE IF EXISTS PCM_TGT_DEV_SCHEDULE CASCADE;
CREATE TABLE PCM_TGT_DEV_SCHEDULE (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    SCHED_SEQ    INTEGER      NOT NULL,
    SCHED_TYPE   VARCHAR(20),
    SCHED_NM     VARCHAR(200),
    PLAN_START_DT VARCHAR(10),
    PLAN_END_DT  VARCHAR(10),
    ACT_END_DT   VARCHAR(10),
    EVAL_ROUND   VARCHAR(10),
    EVAL_PERIOD  VARCHAR(100),
    DELAY_DAYS   INTEGER      DEFAULT 0,
    PROC_YN      CHAR(1)      DEFAULT 'N',
    SORT_ORDER   INTEGER      DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_DEV_SCHED PRIMARY KEY (TEN_ID, TGT_PJT_CD, SCHED_SEQ)
);

-- 1-6. 목표원가 목표수립일정
DROP TABLE IF EXISTS PCM_TGT_SETUP_SCHEDULE CASCADE;
CREATE TABLE PCM_TGT_SETUP_SCHEDULE (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    SETUP_SEQ    INTEGER      NOT NULL,
    DEPT_NM      VARCHAR(100),
    START_DT     VARCHAR(10),
    END_DT       VARCHAR(10),
    ACT_END_DT   VARCHAR(10),
    PROC_YN      CHAR(1)      DEFAULT 'N',
    DELAY_DAYS   INTEGER      DEFAULT 0,
    EMAIL_SENT   CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_SETUP_SCHED PRIMARY KEY (TEN_ID, TGT_PJT_CD, SETUP_SEQ)
);

-- 1-7. 목표원가 등록 (원가항목별 최종목표/절감목표)
DROP TABLE IF EXISTS PCM_TGT_COST_REG CASCADE;
CREATE TABLE PCM_TGT_COST_REG (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    COST_SEQ     INTEGER      NOT NULL,
    COST_ITEM_CD VARCHAR(18),
    COST_ITEM_NM VARCHAR(100),
    DEPT_CD      VARCHAR(18),
    DEPT_NM      VARCHAR(100),
    EC_COST_AMT  NUMERIC(18,2) DEFAULT 0,
    GUIDE_AMT    NUMERIC(18,2) DEFAULT 0,
    FINAL_TGT_AMT NUMERIC(18,2) DEFAULT 0,
    DIFF_AMT     NUMERIC(18,2) DEFAULT 0,
    ADJ_REASON   VARCHAR(500),
    SAVE_TGT_AMT NUMERIC(18,2) DEFAULT 0,
    CONFIRM_YN   CHAR(1)      DEFAULT 'N',
    VIEW_MODE    VARCHAR(10)  DEFAULT 'SUM',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_COST_REG PRIMARY KEY (TEN_ID, TGT_PJT_CD, COST_SEQ)
);

-- 1-8. 목표달성 계획
DROP TABLE IF EXISTS PCM_TGT_ACHV_PLAN CASCADE;
CREATE TABLE PCM_TGT_ACHV_PLAN (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    PLAN_SEQ     INTEGER      NOT NULL,
    COST_ITEM_CD VARCHAR(18),
    COST_ITEM_NM VARCHAR(100),
    EC_COST_AMT  NUMERIC(18,2) DEFAULT 0,
    TGT_COST_AMT NUMERIC(18,2) DEFAULT 0,
    SAVE_TGT_AMT NUMERIC(18,2) DEFAULT 0,
    SAVE_PLAN_AMT NUMERIC(18,2) DEFAULT 0,
    CONFIRM_YN   CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_ACHV_PLAN PRIMARY KEY (TEN_ID, TGT_PJT_CD, PLAN_SEQ)
);

-- 1-9. 목표달성 계획 상세 (절감계획)
DROP TABLE IF EXISTS PCM_TGT_ACHV_PLAN_DTL CASCADE;
CREATE TABLE PCM_TGT_ACHV_PLAN_DTL (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    PLAN_SEQ     INTEGER      NOT NULL,
    DTL_SEQ      INTEGER      NOT NULL,
    LEVEL1       VARCHAR(100),
    LEVEL2       VARCHAR(100),
    LEVEL3       VARCHAR(100),
    SAVE_AMT     NUMERIC(18,2) DEFAULT 0,
    FILE_NM      VARCHAR(500),
    FILE_PATH    VARCHAR(1000),
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_ACHV_PLAN_DTL PRIMARY KEY (TEN_ID, TGT_PJT_CD, PLAN_SEQ, DTL_SEQ)
);

-- 1-10. 목표원가 재산출 (현상원가 연계)
DROP TABLE IF EXISTS PCM_TGT_RECALC CASCADE;
CREATE TABLE PCM_TGT_RECALC (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    RECALC_SEQ   INTEGER      NOT NULL,
    CC_GRP_CD    VARCHAR(18),
    CC_ROUND     VARCHAR(10),
    TGT_PROFIT_RATE NUMERIC(5,2) DEFAULT 0,
    FINAL_TGT_PROFIT_RATE NUMERIC(5,2) DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_RECALC PRIMARY KEY (TEN_ID, TGT_PJT_CD, RECALC_SEQ)
);

-- 1-11. 목표달성 현황
DROP TABLE IF EXISTS PCM_TGT_ACHV_STATUS CASCADE;
CREATE TABLE PCM_TGT_ACHV_STATUS (
    TEN_ID       VARCHAR(18)  NOT NULL,
    TGT_PJT_CD   VARCHAR(18)  NOT NULL,
    PJT_NM       VARCHAR(200),
    BIZ_UNIT     VARCHAR(18),
    PROD_GRP     VARCHAR(18),
    OEM_NM       VARCHAR(100),
    CAR_TYPE     VARCHAR(100),
    EC_TOTAL_AMT NUMERIC(18,2) DEFAULT 0,
    TGT_TOTAL_AMT NUMERIC(18,2) DEFAULT 0,
    CUR_TOTAL_AMT NUMERIC(18,2) DEFAULT 0,
    SAVE_TGT_AMT NUMERIC(18,2) DEFAULT 0,
    SAVE_ACT_AMT NUMERIC(18,2) DEFAULT 0,
    ACHV_RATE    NUMERIC(8,2)  DEFAULT 0,
    ACHV_YN      CHAR(1)      DEFAULT 'N',
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_TGT_ACHV_STATUS PRIMARY KEY (TEN_ID, TGT_PJT_CD)
);

-- ═══════════════════════════════════════════
-- 2. 현상원가 상세 테이블
-- ═══════════════════════════════════════════

-- 2-1. 현상원가 상세정보
DROP TABLE IF EXISTS PCM_CUR_DETAIL CASCADE;
CREATE TABLE PCM_CUR_DETAIL (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    REV_NM       VARCHAR(200),
    FACTORY_DIV  VARCHAR(10),
    FACTORY_CD   VARCHAR(18),
    FACTORY_NM   VARCHAR(100),
    CORP_DIV     VARCHAR(10),
    CORP_CD      VARCHAR(18),
    CORP_NM      VARCHAR(100),
    ATTACH_FILE  VARCHAR(500),
    COMPOSE_YN   CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_DETAIL PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV)
);

-- 2-2. 현상원가 원가코드/판가
DROP TABLE IF EXISTS PCM_CUR_COST_CODE CASCADE;
CREATE TABLE PCM_CUR_COST_CODE (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    COST_SEQ     INTEGER      NOT NULL,
    COST_CD      VARCHAR(18),
    CALC_TARGET  CHAR(1)      DEFAULT 'Y',
    PROD_DESC    VARCHAR(500),
    CURRENCY     VARCHAR(10),
    EST_SELL_PRICE NUMERIC(18,2) DEFAULT 0,
    SOP_YM       VARCHAR(7),
    EOP_YM       VARCHAR(7),
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_COST_CODE PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, COST_SEQ)
);

-- 2-3. 현상원가 수량/할인율
DROP TABLE IF EXISTS PCM_CUR_QTY_DISC CASCADE;
CREATE TABLE PCM_CUR_QTY_DISC (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    QTY_SEQ      INTEGER      NOT NULL,
    COST_CD      VARCHAR(18),
    YEAR_VAL     VARCHAR(4),
    SELL_QTY     NUMERIC(18,2) DEFAULT 0,
    DISC_RATE    NUMERIC(8,4)  DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_QTY_DISC PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, QTY_SEQ)
);

-- 2-4. 현상원가 담당자
DROP TABLE IF EXISTS PCM_CUR_MANAGER CASCADE;
CREATE TABLE PCM_CUR_MANAGER (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    MGR_SEQ      INTEGER      NOT NULL,
    DEPT_DIV     VARCHAR(18),
    MGR_ID       VARCHAR(18),
    MGR_NM       VARCHAR(100),
    ROLE_CD      VARCHAR(10),
    EMAIL        VARCHAR(200),
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_MANAGER PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, MGR_SEQ)
);

-- 2-5. 현상원가 일정
DROP TABLE IF EXISTS PCM_CUR_SCHEDULE CASCADE;
CREATE TABLE PCM_CUR_SCHEDULE (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    SCHED_SEQ    INTEGER      NOT NULL,
    TASK_NM      VARCHAR(200),
    STD_PERIOD   INTEGER      DEFAULT 0,
    START_DT     VARCHAR(10),
    END_DT       VARCHAR(10),
    ACT_END_DT   VARCHAR(10),
    PROC_STS     VARCHAR(10)  DEFAULT 'W',
    DELAY_DAYS   INTEGER      DEFAULT 0,
    SORT_ORDER   INTEGER      DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_SCHEDULE PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, SCHED_SEQ)
);

-- 2-6. 현상원가 BOM
DROP TABLE IF EXISTS PCM_CUR_BOM CASCADE;
CREATE TABLE PCM_CUR_BOM (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    COST_CD      VARCHAR(18)  NOT NULL DEFAULT '',
    BOM_SEQ      INTEGER      NOT NULL,
    PART_NO      VARCHAR(50),
    PART_NM      VARCHAR(200),
    PART_DIV     VARCHAR(10),
    QTY          NUMERIC(18,4) DEFAULT 1,
    RECV_UNIT_YN CHAR(1)      DEFAULT 'N',
    PARENT_SEQ   INTEGER      DEFAULT 0,
    BOM_LEVEL    INTEGER      DEFAULT 1,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_BOM PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, COST_CD, BOM_SEQ)
);

-- 2-7. 현상원가 BOM 맵핑
DROP TABLE IF EXISTS PCM_CUR_BOM_MAP CASCADE;
CREATE TABLE PCM_CUR_BOM_MAP (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    COST_CD      VARCHAR(18)  NOT NULL DEFAULT '',
    MAP_SEQ      INTEGER      NOT NULL,
    CUR_BOM_SEQ  INTEGER,
    PREV_BOM_SEQ INTEGER,
    PREV_COST_CD VARCHAR(18),
    PREV_REV     INTEGER,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_BOM_MAP PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, COST_CD, MAP_SEQ)
);

-- 2-8. 현상원가 부품단가
DROP TABLE IF EXISTS PCM_CUR_PART_PRICE CASCADE;
CREATE TABLE PCM_CUR_PART_PRICE (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    COST_CD      VARCHAR(18)  NOT NULL DEFAULT '',
    PRICE_SEQ    INTEGER      NOT NULL,
    PART_NO      VARCHAR(50),
    PART_NM      VARCHAR(200),
    PART_DIV     VARCHAR(10),
    PIMS_CURRENCY VARCHAR(10),
    PIMS_PRICE   NUMERIC(18,4) DEFAULT 0,
    DESIGN_CURRENCY VARCHAR(10),
    DESIGN_PRICE NUMERIC(18,4) DEFAULT 0,
    PURCHASE_CURRENCY VARCHAR(10),
    PURCHASE_PRICE NUMERIC(18,4) DEFAULT 0,
    CONFIRM_CURRENCY VARCHAR(10),
    CONFIRM_PRICE NUMERIC(18,4) DEFAULT 0,
    LOSS_RATE    NUMERIC(8,4)  DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_PART_PRICE PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, COST_CD, PRICE_SEQ)
);

-- 2-9. 현상원가 라인투자비
DROP TABLE IF EXISTS PCM_CUR_LINE_INVEST CASCADE;
CREATE TABLE PCM_CUR_LINE_INVEST (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    LINE_SEQ     INTEGER      NOT NULL,
    LINE_DIV     VARCHAR(10),
    LINE_CD      VARCHAR(18),
    LINE_NM      VARCHAR(200),
    INVEST_NM    VARCHAR(200),
    PROCESS_CD   VARCHAR(18),
    ACQ_AMT      NUMERIC(18,2) DEFAULT 0,
    ACQ_CURRENCY VARCHAR(10),
    DEPR_START_YM VARCHAR(7),
    CAPA_EA      NUMERIC(18,2) DEFAULT 0,
    AVAIL_RATE   NUMERIC(8,2)  DEFAULT 100,
    USE_RATE     NUMERIC(8,2)  DEFAULT 0,
    BASE_YEAR    VARCHAR(4),
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_LINE_INVEST PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, LINE_SEQ)
);

-- 2-10. 현상원가 라인투자비 상세
DROP TABLE IF EXISTS PCM_CUR_LINE_INVEST_DTL CASCADE;
CREATE TABLE PCM_CUR_LINE_INVEST_DTL (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    LINE_SEQ     INTEGER      NOT NULL,
    DTL_SEQ      INTEGER      NOT NULL,
    ITEM_DESC    VARCHAR(500),
    CURRENCY     VARCHAR(10),
    AMT          NUMERIC(18,2) DEFAULT 0,
    ACQ_YEAR     VARCHAR(4),
    DEPR_START_YM VARCHAR(7),
    CAPA_EA      NUMERIC(18,2) DEFAULT 0,
    USEFUL_LIFE  INTEGER      DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_LINE_INV_DTL PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, LINE_SEQ, DTL_SEQ)
);

-- 2-11. 현상원가 라인 C/T 배정
DROP TABLE IF EXISTS PCM_CUR_LINE_CT CASCADE;
CREATE TABLE PCM_CUR_LINE_CT (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    LINE_SEQ     INTEGER      NOT NULL,
    COST_CD      VARCHAR(18)  NOT NULL DEFAULT '',
    USE_YN       CHAR(1)      DEFAULT 'N',
    EST_CT       NUMERIC(18,4) DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_LINE_CT PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, LINE_SEQ, COST_CD)
);

-- 2-12. 현상원가 기타투자비
DROP TABLE IF EXISTS PCM_CUR_OTHER_INVEST CASCADE;
CREATE TABLE PCM_CUR_OTHER_INVEST (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    INVEST_SEQ   INTEGER      NOT NULL,
    INVEST_NM    VARCHAR(200),
    INVEST_DIV   VARCHAR(18),
    CURRENCY     VARCHAR(10),
    ACQ_AMT      NUMERIC(18,2) DEFAULT 0,
    DEPR_DIV     VARCHAR(18),
    USEFUL_LIFE  INTEGER      DEFAULT 0,
    ACQ_YEAR     VARCHAR(4),
    DEPR_START_YM VARCHAR(7),
    AVAIL_RATE   NUMERIC(8,2)  DEFAULT 100,
    USE_RATE     NUMERIC(8,2)  DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_OTHER_INVEST PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, INVEST_SEQ)
);

-- 2-13. 현상원가 인원계획
DROP TABLE IF EXISTS PCM_CUR_MANPOWER CASCADE;
CREATE TABLE PCM_CUR_MANPOWER (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    MP_SEQ       INTEGER      NOT NULL,
    MP_DIV       VARCHAR(18),
    MP_NM        VARCHAR(200),
    PROCESS_CD   VARCHAR(18),
    CURRENCY     VARCHAR(10),
    AVG_SALARY   NUMERIC(18,2) DEFAULT 0,
    YEAR_VAL     VARCHAR(4)   NOT NULL DEFAULT '',
    HEAD_COUNT   NUMERIC(8,2)  DEFAULT 0,
    LINE_SEQ     INTEGER      DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_MANPOWER PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, MP_SEQ)
);

-- 2-14. 현상원가 제조경비
DROP TABLE IF EXISTS PCM_CUR_MFG_COST CASCADE;
CREATE TABLE PCM_CUR_MFG_COST (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    COST_CD      VARCHAR(18)  NOT NULL DEFAULT '',
    WAGE_INCR_RATE   NUMERIC(8,4) DEFAULT 0,
    PRICE_INCR_RATE  NUMERIC(8,4) DEFAULT 0,
    DIRECT_EXP_RATE  NUMERIC(8,4) DEFAULT 0,
    LABOR_EXP_RATE   NUMERIC(8,4) DEFAULT 0,
    OTHER_MFG_RATE   NUMERIC(8,4) DEFAULT 0,
    MOLD_UNIT_COST   NUMERIC(18,2) DEFAULT 0,
    OUTSRC_UNIT_COST NUMERIC(18,2) DEFAULT 0,
    OUTSRC_RATE      NUMERIC(8,4) DEFAULT 0,
    CALC_DONE_YN     CHAR(1)      DEFAULT 'N',
    DIRECT_LABOR_AMT NUMERIC(18,2) DEFAULT 0,
    INDIRECT_LABOR_AMT NUMERIC(18,2) DEFAULT 0,
    DIRECT_EXP_AMT  NUMERIC(18,2) DEFAULT 0,
    LABOR_EXP_AMT   NUMERIC(18,2) DEFAULT 0,
    OTHER_MFG_AMT   NUMERIC(18,2) DEFAULT 0,
    DEPR_BLDG_AMT   NUMERIC(18,2) DEFAULT 0,
    DEPR_LINE_AMT   NUMERIC(18,2) DEFAULT 0,
    DEPR_OTHER_AMT  NUMERIC(18,2) DEFAULT 0,
    OUTSRC_AMT      NUMERIC(18,2) DEFAULT 0,
    MOLD_AMT        NUMERIC(18,2) DEFAULT 0,
    RND_AMT         NUMERIC(18,2) DEFAULT 0,
    OTHER_EXP_AMT   NUMERIC(18,2) DEFAULT 0,
    TOTAL_MFG_AMT   NUMERIC(18,2) DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_MFG_COST PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, COST_CD)
);

-- 2-15. 현상원가 판매관리비
DROP TABLE IF EXISTS PCM_CUR_SGA_COST CASCADE;
CREATE TABLE PCM_CUR_SGA_COST (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    COST_CD      VARCHAR(18)  NOT NULL DEFAULT '',
    SALE_LABOR_RATE  NUMERIC(8,4) DEFAULT 0,
    TRANSPORT_RATE   NUMERIC(8,4) DEFAULT 0,
    EXPORT_RATE      NUMERIC(8,4) DEFAULT 0,
    QA_RATE          NUMERIC(8,4) DEFAULT 0,
    AD_RATE          NUMERIC(8,4) DEFAULT 0,
    RESEARCH_RATE    NUMERIC(8,4) DEFAULT 0,
    ASSET_RATE       NUMERIC(8,4) DEFAULT 0,
    HR_RATE          NUMERIC(8,4) DEFAULT 0,
    OTHER_RATE       NUMERIC(8,4) DEFAULT 0,
    CALC_DONE_YN     CHAR(1)      DEFAULT 'N',
    SALE_LABOR_AMT   NUMERIC(18,2) DEFAULT 0,
    TRANSPORT_AMT    NUMERIC(18,2) DEFAULT 0,
    EXPORT_AMT       NUMERIC(18,2) DEFAULT 0,
    QA_AMT           NUMERIC(18,2) DEFAULT 0,
    AD_AMT           NUMERIC(18,2) DEFAULT 0,
    RESEARCH_AMT     NUMERIC(18,2) DEFAULT 0,
    ASSET_AMT        NUMERIC(18,2) DEFAULT 0,
    HR_AMT           NUMERIC(18,2) DEFAULT 0,
    OTHER_AMT        NUMERIC(18,2) DEFAULT 0,
    TOTAL_SGA_AMT    NUMERIC(18,2) DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_SGA_COST PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, COST_CD)
);

-- 2-16. 현상원가 손익계산서
DROP TABLE IF EXISTS PCM_CUR_PL_STMT CASCADE;
CREATE TABLE PCM_CUR_PL_STMT (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    VIEW_TYPE    VARCHAR(10)  NOT NULL DEFAULT 'PJT',
    VIEW_KEY     VARCHAR(18)  NOT NULL DEFAULT '',
    PL_SEQ       INTEGER      NOT NULL,
    COST_ITEM    VARCHAR(100),
    YEAR_VAL     VARCHAR(4)   NOT NULL DEFAULT '',
    TOT_AMT      NUMERIC(18,2) DEFAULT 0,
    UNIT_AMT     NUMERIC(18,2) DEFAULT 0,
    RATE_VAL     NUMERIC(8,4)  DEFAULT 0,
    CALC_DONE_YN CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_PL_STMT PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, VIEW_TYPE, VIEW_KEY, PL_SEQ, YEAR_VAL)
);

-- 2-17. 현상원가 차이분석
DROP TABLE IF EXISTS PCM_CUR_DIFF_ANALYSIS CASCADE;
CREATE TABLE PCM_CUR_DIFF_ANALYSIS (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    DIFF_SEQ     INTEGER      NOT NULL,
    DIFF_TYPE    VARCHAR(10)  NOT NULL DEFAULT 'STEP',
    COST_ITEM_CD VARCHAR(18),
    COST_ITEM_NM VARCHAR(100),
    EC_AMT       NUMERIC(18,2) DEFAULT 0,
    CC_AMT       NUMERIC(18,2) DEFAULT 0,
    DIFF_AMT     NUMERIC(18,2) DEFAULT 0,
    DIFF_RATE    NUMERIC(8,4)  DEFAULT 0,
    CUM_EC_AMT   NUMERIC(18,2) DEFAULT 0,
    CUM_CC_AMT   NUMERIC(18,2) DEFAULT 0,
    CUM_DIFF_AMT NUMERIC(18,2) DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_DIFF_ANALYSIS PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, DIFF_SEQ, DIFF_TYPE)
);

-- 2-18. 현상원가 달성도 평가 상세 (부문별)
DROP TABLE IF EXISTS PCM_CUR_ACHV_EVAL_DTL CASCADE;
CREATE TABLE PCM_CUR_ACHV_EVAL_DTL (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    EVAL_SEQ     INTEGER      NOT NULL,
    EVAL_TYPE    VARCHAR(10)  NOT NULL DEFAULT 'DEPT',
    DEPT_NM      VARCHAR(100),
    COST_ITEM_CD VARCHAR(18),
    COST_ITEM_NM VARCHAR(100),
    EC_AMT       NUMERIC(18,2) DEFAULT 0,
    TGT_AMT      NUMERIC(18,2) DEFAULT 0,
    SAVE_TGT_AMT NUMERIC(18,2) DEFAULT 0,
    CUR_AMT      NUMERIC(18,2) DEFAULT 0,
    SAVE_ACT_AMT NUMERIC(18,2) DEFAULT 0,
    ACHV_RATE    NUMERIC(8,2)  DEFAULT 0,
    ACHV_YN      CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_ACHV_EVAL_DTL PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, EVAL_SEQ, EVAL_TYPE)
);

-- 2-19. 현상원가 실적 달성도 평가
DROP TABLE IF EXISTS PCM_CUR_ACT_EVAL CASCADE;
CREATE TABLE PCM_CUR_ACT_EVAL (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    TGT_COST_CD  VARCHAR(18)  NOT NULL DEFAULT '',
    EVAL_SEQ     INTEGER      NOT NULL,
    COST_ITEM_NM VARCHAR(100),
    EC_AMT       NUMERIC(18,2) DEFAULT 0,
    TGT_AMT      NUMERIC(18,2) DEFAULT 0,
    SAVE_TGT_AMT NUMERIC(18,2) DEFAULT 0,
    ACT_AMT      NUMERIC(18,2) DEFAULT 0,
    SAVE_ACT_AMT NUMERIC(18,2) DEFAULT 0,
    ACHV_RATE    NUMERIC(8,2)  DEFAULT 0,
    ACHV_YN      CHAR(1)      DEFAULT 'N',
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_ACT_EVAL PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, TGT_COST_CD, EVAL_SEQ)
);

-- 2-20. 현상원가 실적 재료비 추정
DROP TABLE IF EXISTS PCM_CUR_ACT_MATERIAL CASCADE;
CREATE TABLE PCM_CUR_ACT_MATERIAL (
    TEN_ID       VARCHAR(18)  NOT NULL,
    CC_PJT_CD    VARCHAR(18)  NOT NULL,
    CC_REV       INTEGER      NOT NULL DEFAULT 1,
    TGT_COST_CD  VARCHAR(18)  NOT NULL DEFAULT '',
    MAT_SEQ      INTEGER      NOT NULL,
    PART_NO      VARCHAR(50),
    PART_NM      VARCHAR(200),
    PIMS_CURRENCY VARCHAR(10),
    PIMS_PRICE   NUMERIC(18,4) DEFAULT 0,
    EVAL_CURRENCY VARCHAR(10),
    EVAL_EXCH_RATE NUMERIC(18,6) DEFAULT 1,
    EVAL_PRICE   NUMERIC(18,4) DEFAULT 0,
    EST_MAT_COST NUMERIC(18,2) DEFAULT 0,
    RMK          VARCHAR(1000),
    STS          CHAR(1)      DEFAULT 'T',
    REGR_ID      VARCHAR(18),
    REG_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    MODR_ID      VARCHAR(18),
    MOD_DTTM     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PCM_CUR_ACT_MATERIAL PRIMARY KEY (TEN_ID, CC_PJT_CD, CC_REV, TGT_COST_CD, MAT_SEQ)
);
