-- ============================================================
-- 기준정보 관리 테이블 (법인세율 ~ 절감대상 담당부서)
-- ============================================================
SET search_path TO asyoucost;

-- ■ 법인세율
CREATE TABLE IF NOT EXISTS asyoucost.PCM_CORP_TAX (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    COUNTRY_NM  VARCHAR(100),
    BASE_YEAR   VARCHAR(4),
    APPLY_YEAR  VARCHAR(4),
    TAX_RATE    NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_CORP_TAX PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ CRP (Country Risk Premium)
CREATE TABLE IF NOT EXISTS asyoucost.PCM_CRP (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    COUNTRY_NM  VARCHAR(100),
    BASE_YEAR   VARCHAR(4),
    CRP_VAL     NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_CRP PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ WACC Betau
CREATE TABLE IF NOT EXISTS asyoucost.PCM_BETAU (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    BASE_YEAR   VARCHAR(4),
    BIZ_UNIT    VARCHAR(18),
    BETAU_VAL   NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_BETAU PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 기존 생산라인
CREATE TABLE IF NOT EXISTS asyoucost.PCM_PROD_LINE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    BASE_YEAR   VARCHAR(4),
    PLANT_CD    VARCHAR(50),
    LINE_NM     VARCHAR(200),
    PROD_NM     VARCHAR(200),
    CAPACITY    BIGINT,
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_PROD_LINE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 손익 항목 (트리)
CREATE TABLE IF NOT EXISTS asyoucost.PCM_PL_ITEM (
    TEN_ID      VARCHAR(18)  NOT NULL,
    ITEM_CD     VARCHAR(50)  NOT NULL,
    ITEM_NM     VARCHAR(200),
    UP_ITEM_CD  VARCHAR(50),
    ITEM_TYPE   CHAR(1)      DEFAULT 'V',
    LVL         INTEGER      DEFAULT 1,
    SORT_NO     INTEGER      DEFAULT 0,
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_PL_ITEM PRIMARY KEY (TEN_ID, ITEM_CD)
);

-- ■ 사업 실적 비율
CREATE TABLE IF NOT EXISTS asyoucost.PCM_BIZ_PERF_RATE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    BASE_YEAR   VARCHAR(4),
    CORP_CD     VARCHAR(50),
    BIZ_UNIT    VARCHAR(18),
    ITEM_CD     VARCHAR(50),
    PERF_RATE   NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_BIZ_PERF_RATE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 환율
CREATE TABLE IF NOT EXISTS asyoucost.PCM_EXCH_RATE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    APPLY_YEAR  VARCHAR(4),
    FROM_CUR    VARCHAR(10),
    TO_CUR      VARCHAR(10),
    EXCH_RATE   NUMERIC(18,6),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_EXCH_RATE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 인상율
CREATE TABLE IF NOT EXISTS asyoucost.PCM_RAISE_RATE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    APPLY_YEAR  VARCHAR(4),
    CORP_CD     VARCHAR(50),
    PLANT_CD    VARCHAR(50),
    ITEM_CD     VARCHAR(50),
    RAISE_RATE  NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_RAISE_RATE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 표준 일정
CREATE TABLE IF NOT EXISTS asyoucost.PCM_STD_SCHEDULE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    TASK_NM     VARCHAR(200),
    LEAD_DAYS   INTEGER,
    DEPT_CD     VARCHAR(50),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_STD_SCHEDULE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 원가 절감 활동 유형
CREATE TABLE IF NOT EXISTS asyoucost.PCM_COST_REDU_TYPE (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    ITEM_CD     VARCHAR(50),
    CLASS1      VARCHAR(200),
    CLASS2      VARCHAR(200),
    CLASS3      VARCHAR(200),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_COST_REDU_TYPE PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ ERP 제조원가 계정 매핑
CREATE TABLE IF NOT EXISTS asyoucost.PCM_ERP_ACCT_MAP (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    FROM_CD     VARCHAR(50),
    TO_CD       VARCHAR(50),
    ITEM_NM     VARCHAR(200),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_ERP_ACCT_MAP PRIMARY KEY (TEN_ID, SEQ_NO)
);

-- ■ 절감대상 원가항목 및 담당부서
CREATE TABLE IF NOT EXISTS asyoucost.PCM_REDU_TGT_DEPT (
    TEN_ID      VARCHAR(18)  NOT NULL,
    SEQ_NO      SERIAL,
    ITEM_NM     VARCHAR(200),
    DTL_ITEM_NM VARCHAR(200),
    DEPT_CD     VARCHAR(50),
    RESP_RATE   NUMERIC(10,4),
    RMK         VARCHAR(1000),
    REGR_ID     VARCHAR(50),  REG_DTTM  TIMESTAMPTZ,
    MODR_ID     VARCHAR(50),  MOD_DTTM  TIMESTAMPTZ,
    CONSTRAINT PK_PCM_REDU_TGT_DEPT PRIMARY KEY (TEN_ID, SEQ_NO)
);
